language: python
dist: xenial
cache: pip
python:
  - 3.7
env:
  global:
    - secure: "VNgpd/TFAkLGjWZzRBWxujDHktdvp2Fg9D8PbGmr/pbmLcJS3a5pf6po1T/\
               GJgioh8SI1TgPURjku5t48VHN18HoMBzABBSZ4C7cUjpNQlJMPKhWCZKmIJ\
               alcS7yEFlTk8QqEBNh1twUFxHLxW/B9j4N5wHjOileocoo4EvhYUA="
addons:
  apt:
    packages:
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - graphviz
      - texlive-xetex
      - texlive-fonts-recommended
      - fonts-freefont-otf
      - latexmk
      - lmodern
stages:
  - deploy
matrix:
  include:
    - stage: deploy
      env:
        -
      script:
        - python setup.py build_sphinx -W -b html
        - git clone https://github.com/diofant/diofant.github.io.git sphinx_docs
        - rm -rf sphinx_docs/.git
        - rsync -a --delete build/sphinx/html/ sphinx_docs/en/latest/
      deploy:
        - provider: pages
          repo: diofant/diofant.github.io
          local-dir: sphinx_docs
          target-branch: master
          github-token: $GITHUB_TOKEN
          skip-cleanup: true
          keep-history: true
          on:
            branch: master
before_install:
  - pip uninstall -y pytest attrs
  - pip install --pre -U gmpy2
install:
  - travis_wait pip install -U .[interactive,develop,gmpy,exports,plot,docs]
script:
  - echo
notifications:
  email: false
