[build-system]
requires = ['setuptools>=42', 'wheel', 'setuptools_scm[toml]>=6.0']
build-backend = 'setuptools.build_meta'
[tool.setuptools_scm]
[tool.isort]
lines_after_imports = 2
skip = ['diofant/core/expr.py',
        'diofant/__init__.py',
        'diofant/core/__init__.py',
        'diofant/polys/__init__.py']
atomic = true
[tool.pylint.MASTER]
jobs = 0
init_hook = 'import sys; sys.setrecursionlimit(2000)'  # PyCQA/pylint#2388
[tool.pylint.'MESSAGES CONTROL']
disable = ['blacklisted-name',
           'invalid-name',
           'missing-docstring',
           'unidiomatic-typecheck',
           'bad-mcs-method-argument',
           'line-too-long',
           'too-many-lines',
           'wrong-spelling-in-comment',
           'wrong-spelling-in-docstring',
           'wrong-import-position',
           'too-many-star-expressions',
           'non-iterator-returned',
           'relative-beyond-top-level',
           'no-name-in-module',
           'unbalanced-tuple-unpacking',
           'no-member',
           'not-callable',
           'no-value-for-parameter',
           'invalid-unary-operand-type',
           'parameter-unpacking',
           'import-star-module-level',
           'bad-inline-option',
           'use-symbolic-message-instead',
           'no-self-use',
           'no-staticmethod-decorator',
           'cyclic-import',
           'duplicate-code',
           'too-many-ancestors',
           'too-many-instance-attributes',
           'too-few-public-methods',
           'too-many-public-methods',
           'too-many-return-statements',
           'too-many-branches',
           'too-many-arguments',
           'too-many-locals',
           'too-many-statements',
           'too-many-boolean-expressions',
           'too-many-nested-blocks',
           'redefined-argument-from-local',
           'no-else-return',
           'trailing-comma-tuple',
           'inconsistent-return-statements',
           'chained-comparison',
           'dangerous-default-value',
           'duplicate-key',
           'protected-access',
           'arguments-differ',
           'abstract-method',
           'no-init',
           'relative-import',
           'fixme',
           'global-variable-undefined',
           'global-variable-not-assigned',
           'global-statement',
           'global-at-module-level',
           'unused-argument',
           'redefined-outer-name',
           'redefined-builtin',
           'redefine-in-handler',
           'undefined-loop-variable',
           'cell-var-from-loop',
           'raising-format-tuple',
           'keyword-arg-before-vararg',
           'missing-format-argument-key',
           'unused-format-string-argument',
           'next-method-called',
           'import-outside-toplevel',
           'no-else-continue',
           'arguments-out-of-order',
           'consider-using-f-string',
           'use-implicit-booleaness-not-comparison']
[tool.pytest.ini_options]
doctest_optionflags = ['ELLIPSIS', 'NORMALIZE_WHITESPACE',
                       'IGNORE_EXCEPTION_DETAIL']
addopts = """\
          --durations=20 -r X --doctest-glob='*.rst' \
          --cov-config=pyproject.toml -n auto \
          """
norecursedirs = ['build', '.eggs', '.git']
timeout = 1000
xfail_strict = true
filterwarnings = ['ignore::UserWarning',
                  'error::DeprecationWarning']
[tool.coverage.run]
branch = true
omit = ['conftest.py',
        'diofant/tests/*',
        'diofant/tests/*/*']
parallel = true
[tool.coverage.html]
directory = 'build/coverage/html'
[tool.coverage.report]
exclude_lines = ['pragma: no cover',
                 'except NotImplementedError',
                 'raise NotImplementedError',
                 'return NotImplemented']
show_missing = true
[tool.mypy]
follow_imports = 'silent'
[[tool.mypy.overrides]]
module = ['IPython.*', 'gmpy2', 'matplotlib', 'mpmath.*', 'pexpect',
          'scipy.*', 'traitlets.*']
ignore_missing_imports = true
